
name: testgen

x-common-variables: &common-variables
  TESTGEN_USERNAME: admin
  TESTGEN_PASSWORD: uH6Ktkjfka7I
  TG_DECRYPT_SALT: Haa07cNH8b62
  TG_DECRYPT_PASSWORD: 5Vm11kgsttfz
  TG_JWT_HASHING_KEY: ycIduF3LXZyhd7FsBjFJGCxrBCeOeTl270UdP0ny0go=
  TG_METADATA_DB_HOST: postgres
  TG_TARGET_DB_TRUST_SERVER_CERTIFICATE: yes
  TG_EXPORT_TO_OBSERVABILITY_VERIFY_SSL: no
  TG_INSTANCE_ID: feb4b24911cd4f84
  TG_ANALYTICS: yes


services:
  engine:
    image: datakitchen/dataops-testgen:v4
    container_name: testgen
    environment: *common-variables
    volumes:
      - testgen_data:/var/lib/testgen

    ports:
      - 8501:8501
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
    networks:
      - datakitchen

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=uH6Ktkjfka7I
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 8s
      timeout: 5s
      retries: 3
    networks:
      - datakitchen

volumes:
  postgres_data:
  testgen_data:

networks:
  datakitchen:
    name: datakitchen-network
    external: true
